-- SOLO LECTURA. Dice cuáles de las tablas que la migración quiere crear ya
-- existen en la base, y por tanto fueron saltadas por IF NOT EXISTS.
SELECT table_name AS ya_existe
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'actividades_pesv',
    'aprobaciones_accion',
    'bonificaciones_backup',
    'bono_config_visual',
    'canvas_anotacion',
    'certificacion_envio',
    'certificado_archivo',
    'certificado_tercero',
    'ciclos_seguimiento_eficacia',
    'configuracion_descuento_tercero',
    'custom_places',
    'evidencias_eficacia_cierre',
    'excesos_velocidad',
    'historial_estado_liquidacion_nomina',
    'historial_estado_liquidacion_tercero_final',
    'inducciones_visitantes',
    'invitaciones_usuario',
    'liquidacion_chat_mensaje',
    'liquidacion_ingreso_transmeralda',
    'liquidacion_ingreso_transmeralda_concepto',
    'liquidacion_ingreso_transmeralda_fila',
    'liquidacion_recordatorio',
    'liquidacion_tercero_adicional_periodo_snapshot',
    'liquidacion_tercero_concepto',
    'liquidacion_tercero_envio',
    'liquidacion_tercero_final',
    'liquidacion_tercero_final_adicional',
    'liquidacion_tercero_final_concepto',
    'liquidacion_tercero_final_item',
    'liquidacion_tercero_final_propietario',
    'liquidacion_tercero_final_snapshot',
    'liquidacion_tercero_ocasional',
    'liquidacion_tercero_ocasional_adicional',
    'liquidacion_tercero_ocasional_concepto',
    'liquidacion_tercero_ocasional_draft',
    'liquidacion_tercero_ocasional_item',
    'liquidacion_tercero_ocasional_snapshot',
    'nomina_envio',
    'nomina_periodo_snapshot',
    'preoperacionales',
    'registro_dia_laboral_bono',
    'salidas_no_conformes',
    'seguimientos_causa',
    'seguimientos_correccion_inmediata',
    'tercero_token',
    'tipo_certificado'
  )
ORDER BY 1;
